### ISSUE TITLE
Deletion (<del>) is not rendered if the number (@n) of the line is added.

### ISSUE THREAD

**Issue by federicaspinelli** [evt-project/evt-viewer#112]
When using both `<note>` and `<del>` in lines of poetry, if we give the line an `@n`, the inline note marker appears but the deletion is not rendered in EVT. If we remove the `@n` from `<l>`, the `<del>` is rendered but the note marker disappears and the `<note>` text appears inline.

This is a sample TEI encoding:

`<l n="7">`To hear`<note>`blah blah`</note>` the wild wind `<del>`rushing`</del>` by`</l>`
`<l>`With`<note>`yadda yadda`</note>` never `<del>`ending`</del>` roar;`</l>`

and in the attached image you can see how EVT 2 beta2 renders it:

![image001](https://user-images.githubusercontent.com/16621283/105574281-c1d46600-5d63-11eb-8912-407afff78a44.jpeg)

**Comment by RobertoRDT** [comment]
Adding the sample files included in the original mail by Justin Tonra (2021-01-22).

[EVT del query.zip](https://github.com/evt-project/evt-viewer/files/5859975/EVT.del.query.zip)

**Comment by ChiaraDipi** [comment]
In reality the problem is reversed: when adding the `@n` attribute, for some reason nested children are not correctly parsed and rendered. If you analyze the HTML you'll see that both `<note>` and `<del>` are not correctly transformed into `<span>`s. `del` seems to be correctly rendered because this is the browser's default rendering for the html element `<del>`.
In the line with `@n` the xml element is almost correctly transformed: there is just a problem with the class name: it is all uppercase thus it does not follows the rules defined for the element with class `.del` (all smallcase). We should fix also this problem. 
Anyway if you want, you can add your own style rule like:
```
.DEL {
   text-decoration: line-through;
}
```

More over, even for `.del` elements, in critical edition there is a rule which remove this particular layout.
