### ISSUE TITLE
Uncommon characters are shown in the critical entries exponents

### ISSUE THREAD

**Issue by ChiaraMartignano** [evt-project/evt-viewer#5]
See sample:
![exponents_bug](https://user-images.githubusercontent.com/23243170/46541375-27af3200-c8bc-11e8-9a41-7bfc69c4cef5.png)

**Comment by RobertoRDT** [comment]
This is due to the use of all available characters instead of only the proper A-Z letters. Should be solved by having the alphabetic exponents for apparatus entries restart with each paragraph (for prose texts) or, probably better, simply restart after 'z' has been reached (prose and verse texts). Paragraph numbering is fundamental to be able to reference unambiguously to specific apparatus entries in prose texts.

**Comment by ChiaraMartignano** [comment]
Bug fixed.
